### ISSUE TITLE
Can't install the latest functional 1.6-0 from Luarocks

### ISSUE THREAD

**Issue by FractalU** [wqferr/functional#37] opened 2024-10-29 16:38 UTC
When installing functional from Luarocks using `luarocks install functional` it produces the following error.
```
Installing https://luarocks.org/functional-1.6-0.src.rock

Error: Couldn't extract archive C:\msys64\tmp\luarocks_functional-1.6-0-484/functional: unrecognized filename extension
```
Also, when I download the rock manually from https://luarocks.org/manifests/wqferr/functional-1.6-0.src.rock I wasn't able to extract the `functional` directory inside that rock. The only things I was able to extract are the rockspec and a `functional` file which contains html content. That wasn't the case with functional 1.5-1. From the rock file from https://luarocks.org/manifests/wqferr/functional-1.5-1.src.rock I was able to extract both the rockspec and the `functional` directory instead of the `functional` file.

From investigating the rockspec I recognize that the `URL` is set to `https://github.com/wqferr/functional`. It's under `https://` instead of `git://` while pointing to the Github repo of functional. I see the change in the commit https://github.com/wqferr/functional/commit/16452110635d20b8c616cacc5c71875c67d88778. The correct way is to use `git://`, not `https://` because if the URL is under `https://` then Luarocks erroniously thinks that it points to an archive. If the `URL` is under `git://` then Luarocks knows that it points to a git repo. This subtlety isn't explained well in the Luarocks documentation under https://github.com/luarocks/luarocks/wiki/Rockspec-format#build-rules.

My proposal to this issue is to revert the commit https://github.com/wqferr/functional/commit/16452110635d20b8c616cacc5c71875c67d88778 so that the URL is under `git://` instead of `https://` and to update `functional` to `1.6.1` with the rockspec version `1.6-1`.

Btw. I'm still using functional 1.5.0 because I didn't like the lambda syntax addition. So I didn't bother with functional 1.6 much. I'm also not using Luarocks command line and instead manually download the rocks from the Luarocks website. That's why I wasn't aware that Luarocks couldn't install the latest version of functional for so long. Though I was aware back then that `functional-1.6-0.src.rock` was malformed and that the `functional` directory couldn't be extracted from it.

**Comment by FractalU** [comment] 2024-10-29 17:14
Another thing to mention is that I see `functional-1.6-0.all.rock` in this repo which I find it to be rather odd. I haven't seen a `*.all.rock` file in any other Lua project so far. I there a reason to have `functional-1.6-0.all.rock`?

**Comment by wqferr** [comment] 2024-10-29 18:02
The reason is probably a late-night "git add -A" that shouldn't have been made. I need to leave for about an hour and have a very important group meeting (TTRPG session) tonight, but I'll try to look into this inbetween.

If that's not enough time I'll let you know here, then I'll get back to it tomorrow.

Thanks for letting me know! This has probably been an issue for a while now and no one had brought it up.

**Comment by wqferr** [comment] 2024-10-29 23:07
Finally back home, sorry about that. Got sidetracked when the meeting was canceled, so now I can properly focus on this.

**Comment by wqferr** [comment] 2024-10-29 23:36
I believe the issue is solved, @FractalU , thank you to bringing it to my attention! Whenever you have the time, could you please double check it is indeed fixed so I can close this issue?

**Comment by FractalU** [comment] 2024-10-30 02:46
@wqferr The commit looks correct to me. `git://` is now being used instead of `https://`, the version number has been updated from `1.6-0` to `1.6.0-1` and `functional-1.6-0.all.rock` has been removed. Originally, I thought the new version to be `1.6-1` but the currently used `1.6.0-1` seems to be more correct, because the dash part indicates that there is only a new iteration such as adjusting the rockspec. The version is still `1.6.0`. Personally, I find the commit message `Fix rockspec using https:// instead of git://` confusing. Could it also be read that `https//` should be used instead of `git://`? Maybe have clearer message?

In addition, I checked whether I was able to install functional now and it worked.

Here the output
```
$ luarocks install functional
Installing https://luarocks.org/functional-1.6.0-1.src.rock

functional 1.6.0-1 depends on lua >= 5.1, < 5.5 (5.4-1 provided by VM)
cp -t "C:/msys64/ucrt64/lib/luarocks/rocks-5.4/functional/1.6.0-1/lua" functional.lua functional.d.t
l
functional 1.6.0-1 is now installed in C:/msys64/ucrt64 (license: MIT)

```

**Comment by wqferr** [comment] 2024-10-30 10:31
You are correct again regarding the commit message. Don't commit while tired, kids!

Apologies for all the mishaps, and I hope the library will be of use to you.

**Comment by FractalU** [comment] 2024-10-30 15:20
@wqferr  Well, you can amend the last commit message with the folling command
```
git commit --amend -m "New and correct message"
```
Then you can force push this commit to this repo with the folling command
```
git push --force origin master
```
The amend feature in git is exactly for this type of situation.

**Comment by wqferr** [comment] 2024-10-30 16:29
I considered it, but wouldn't that force people to force pull if they already had it cloned on that commit?

For any future changes, I mean.

**Comment by FractalU** [comment] 2024-10-30 18:13
Honestly, I don't really know what happens for the person who pulled the last commit before the amended one has been pushed. Based from the answers of the internet that person is gonna have a hard time. But I think the likelihood of that happening is very low, because functional isn't popular right now and you're the only maintainer of this repo. Also there is zero public forks of this repo. Sure, it might be a bit risky. Amending commit message is really bad for collaborative development, because each amended commit rewrites history.

There is a safer way. Just make another commit with the correct message. The command looks like follows.
```
git commit --allow-empty -m "New and correct message"
```
The third option is to just leave as it is and close this issue. The choice is on you.

**Comment by wqferr** [comment] 2024-10-30 19:51
I opted for the safe option of not rewriting history. Hopefully the commit logs will be clear enough to any readers. I also acknowledged your contributions in the new commit message, apologies for not doing it in the commit proper.

Are there any pending problems related to this issue? Can I safely close it?

**Comment by FractalU** [comment] 2024-10-30 20:48
The safe approach is indeed really good. I'm going to take it as well if I pushed a commit with a bad message to a public repo.

The issue has been resolved. You can close it.

**Comment by wqferr** [comment] 2024-10-30 20:56
Thank you again for bringing it to my attention.

**Closed as completed by wqferr** 2024-10-30 20:56 UTC
